# Generated by Django 4.2.3 on 2023-11-09 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_wallet_balance_wishlists'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlists',
        ),
    ]
