# Generated by Django 4.2.3 on 2023-11-09 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_category_offer'),
        ('accounts', '0007_wishlists'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wishlists',
            new_name='Wishlist',
        ),
    ]
