# Generated by Django 4.2.3 on 2023-09-24 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_delete_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'COD'), ('Razorpay', 'Razorpay')], max_length=100),
        ),
    ]
