# Generated by Django 4.2.3 on 2023-08-03 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_delete_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='color',
        ),
        migrations.DeleteModel(
            name='Color',
        ),
    ]
