# Generated by Django 4.2.3 on 2023-08-21 10:49

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_image_alter_productimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='Product',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='products.Product',
            ),
        ),
    ]
