# Generated by Django 4.2.3 on 2023-08-21 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_size_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='Product',
        ),
    ]
