# Generated by Django 4.2.3 on 2023-09-27 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_productvariant_stock_alter_size_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Color',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='color',
        ),
    ]
